//  actions
const GET_COUNTRIES = "GET_COUNTRIES";
const GET_COUNTRIES_SUCCESS = "GET_COUNTRIES_SUCCESS";
const GET_COUNTRIES_ERROR = "GET_COUNTRIES_ERROR";
const GET_NEW_COUNTRIES = "GET_NEW_COUNTRIES";
const SET_COUNTRIES = "SET_COUNTRIES";
const SET_COUNTRIES_SUCCESS = "SET_COUNTRIES_SUCCESS";
const GET_NEW_SEARCHED_DATA = "GET_NEW_SEARCHED_DATA";
const SET_SEARCHED_DATA = "SET_SEARCHED_DATA";
const SET_SEARCHED_DATA_SUCCESS = "SET_SEARCHED_DATA_SUCCESS";
const DELETE_SEARCHED_DATA = "DELETE_SEARCHED_DATA";

// 정렬 관련 actions
const SET_ASCENDING_STATUS = "SET_ASCENDING_STATUS";

export {
    GET_COUNTRIES_ERROR,
    GET_COUNTRIES,
    GET_COUNTRIES_SUCCESS,
    SET_COUNTRIES,
    SET_COUNTRIES_SUCCESS,
    SET_SEARCHED_DATA,
    SET_SEARCHED_DATA_SUCCESS,
    SET_ASCENDING_STATUS,
    GET_NEW_COUNTRIES,
    GET_NEW_SEARCHED_DATA,
    DELETE_SEARCHED_DATA
}